### ISSUE TITLE
How to add a custom unit

### ISSUE THREAD

**Issue by andrtose** [LZorglub/Measure#1]
Dear all,

this is not am issue I think, I've the need to create my converter and add Calories unit. Is there a way to do so?

many thanks,
Andrea

**Comment by LZorglub** [comment]
Hi Andrea,

Calorie is an unit of energy. So you can create your own class inherited from Joule and specify the converter like this :

```
class Calorie : Joule
{
    public Calorie()
    {
        this._symbol = "cal";
        this._baseConverter = new MultiplyConverter(4.184);
    }
}
```

To convert your unit, you can use ConvertTo methods : 

```
        Calorie cal = new Calorie();
        var qtyCal = 1 * cal;
        Console.WriteLine(qtyCal.ConvertTo<Joule>());
```

Regards
